---
title: "Prediction on Weight Lifting Exercises"
author: "Zongyuan He"
date: "18 Jan 2015"
output: html_document
---

##Summary##



##Exploratory Analysis##

In this analyss we will use WLE[1] dataset to perform the model fitting.

First, we load the training data which was devided before and perform some exploratory analysis.

```{r prepare_training, echo=TRUE}
if(file.access("pml-training.csv", mode = 4) == -1){
    download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", "pml-training.csv", method="curl")
    }
pml_training <- read.csv("pml-training.csv")
```

```{r explore_training, echo=TRUE}
library(caret, quietly = TRUE)
predictors <- names(pml_training)[c(-1,-2,-160)]

```

##Model Building##

##Cross Validation##

##Expected Out of Sample Error Rate##

##Reference##

[1] Velloso, E.; Bulling, A.; Gellersen, H.; Ugulino, W.; Fuks, H. Qualitative Activity Recognition of Weight Lifting Exercises. Proceedings of 4th International Conference in Cooperation with SIGCHI (Augmented Human '13) . Stuttgart, Germany: ACM SIGCHI, 2013.

Read more: http://groupware.les.inf.puc-rio.br/har#ixzz3PA56n1ax
